CHANGELOG.md, arches_references/media/js/views/components/plugins/controlled-list-manager.js, arches_references/src/arches_references/components/ControlledListsMain.vue, arches_references/src/arches_references/components/MainSplitter.vue, arches_references/src/arches_references/components/tree/AddDeleteControls.vue, arches_references/src/arches_references/components/tree/ListTree.vue, arches_references/src/arches_references/components/tree/ListTreeControls.vue, arches_references/src/arches_references/components/tree/MoveRow.vue, arches_references/src/arches_references/components/tree/TreeRow.vue, arches_references/src/arches_references/constants.ts, arches_references/src/arches_references/plugins/ControlledListManager.vue, arches_references/src/arches_references/routes.ts, arches_references/src/arches_references/utils.ts, arches_references/urls.py, arches_references/views.py, package-lock.json, package.json
Natural forward and back navigation is now supported when interacting with lists & items. Allows resolving the default item URIs generated in #17.
- Isolate component that renders the router (was getting double toast / confirm popups)
- Remove trailing slashes from controlled lists routes
- Move name entry field reset to more logical place
Closes #4
=> Implement front-end routing

arches_references/src/arches_references/components/editor/ImageMetadata.vue, arches_references/src/arches_references/components/editor/ValueEditor.vue, arches_references/src/arches_references/components/tree/ActionBanner.vue, arches_references/src/arches_references/components/tree/ListTree.vue, arches_references/src/arches_references/components/tree/TreeRow.vue
Use vue 3.5 [syntax](https://vuejs.org/api/composition-api-helpers.html#usetemplateref) for declaring template refs.
**Testing instructions**
- Visit the elements with this functionality (e.g. input boxes in the tree or datatables) and ensure they still receive focus when mounted.
=> Declare template refs with `useTemplateRef()`

arches_references/datatypes/datatypes.py, arches_references/models.py, arches_references/querysets.py, tests/reference_datatype_tests.py
=> Ingest string values and perform listitem lookup #40

arches_references/datatypes/datatypes.py, arches_references/models.py, tests/reference_datatype_tests.py
Resolves #42 
(This is following same pattern present in the [concept-list datatype](https://github.com/archesproject/arches/blob/a8e97834ff8e6e9658e8e82d1bc7c8871258cc3d/arches/app/datatypes/concept_types.py#L468-L472) get_display_value method)
=> Guard against null values #42

arches_references/src/arches_references/components/tree/ListTree.vue, package-lock.json
- Remove ugly workaround for lazy filtering on labels in selected language
- Cope with primevue 4.1 class name change
- Save labels in multiple languages
- Switch the "show labels in:" language selection inside the tree
- Label filtering should still search on the selected language
- Bolding of search results still works
=> Add primevue 4.1 compat

.github/actions/build-and-test-branch/action.yml
Cope with changes to the github action template merged in #10079.
The github action only sets up a test db, not a real db. The system check in archesproject/arches#10079 expects there to be a real db, so we need to skip system checks in a couple places where we're not intending to run them. The first place is just there to generate the frontend config file.
=> Adjust github action template

arches_references/media/js/viewmodels/reference-select.js, arches_references/templates/views/components/widgets/reference-select.htm, tests/cli_tests.py, tests/fixtures/data/concept_node_migration_test_data.json
Allow user to specify default value
=> Allow user to specify default value

arches_references/management/commands/controlled_lists.py, tests/cli_tests.py, tests/fixtures/data/concept_node_migration_test_data.json
=> Improve concept node migration

arches_references/media/js/views/components/plugins/controlled-list-manager.js, arches_references/src/arches_references/components/editor/ItemHeader.vue, arches_references/src/arches_references/components/editor/ReferenceNodeLink.vue, arches_references/src/arches_references/components/misc/ControlledListSplash.vue, arches_references/src/arches_references/components/tree/ListTree.vue, arches_references/src/arches_references/components/tree/ListTreeControls.vue
To test, use the dark mode toggle in the lingo UI, then visit the controlled list manager.
=> Add dark mode compatibility

arches_references/src/arches_references/api.ts, arches_references/views.py
=> Update controlled_lists endpoint to accept node aliases

arches_references/media/js/views/components/plugins/controlled-list-manager.js, arches_references/src/arches_references/components/ControlledListsMain.vue, arches_references/src/arches_references/components/MainSplitter.vue, arches_references/src/arches_references/components/editor/ImageMetadata.vue, arches_references/src/arches_references/components/editor/ValueEditor.vue, arches_references/src/arches_references/components/tree/ListTree.vue, arches_references/src/arches_references/components/tree/PresentationControls.vue, arches_references/templates/views/components/plugins/controlled-list-manager.htm
- [Avoid rendering language picker if arches object is missing](https://github.com/archesproject/arches-references/commit/25fbef53fd9b37895d06343a75c7eb459432efe5)(important for lingo, which doesn't have `arches.languages`)
- [Avoid wrapping edit controls](https://github.com/archesproject/arches-references/commit/95261615d735f19af50037d20f8460628ba9aca4)
- [Improve position of filter icon](https://github.com/archesproject/arches-references/commit/df8ebb47c49a460ac67d8a896511d83ad1c65be8)
- [Hide injection of selected language under if](https://github.com/archesproject/arches-references/pull/56/commits/cfdf325d24c50973744a444c9303b3271119a16e) (lingo doesn't implement language selection)
=> Style cleanups

arches_references/datatypes/datatypes.py, arches_references/media/js/viewmodels/reference-select.js, arches_references/models.py, tests/reference_datatype_tests.py
As #45 mentions, we didn't have validation against unexpected keys in the reference tile data, so that's how we ended up with `list_id` and `listid`.
We could roll our own solution for this, but I'm suggesting that one approach would be to just use python dataclasses for this so that we have one central place to define the expected keys. This made the validate() method much easier to rewrite. We could also make use of the `frozen` feature if we want immutable python objects later.
There's a bit of fiddliness around transforming error messages into something that can be localized, but if we like this pattern we can probably factor that out into something reusable with other datatypes.
Intended to be tested with the partner lingo PR: https://github.com/archesproject/arches-lingo/pull/208 …
=> Create dataclass for reference datatype and improve validation #45

arches_controlled_lists/datatypes/datatypes.py, arches_controlled_lists/migrations/0001_initial.py, arches_controlled_lists/models.py, arches_controlled_lists/settings.py, pyproject.toml, tests/cli_tests.py, tests/fixtures/data/concept_node_migration_test_data.json, tests/fixtures/data/polyhierarchical_collections.json
We need to loosen the arches pin to be able to unblock lingo PRs, see failing [action](https://github.com/archesproject/arches-lingo/actions/runs/13662252012)
=> Undo arches pin, remove REST framework cruft

arches_controlled_lists/management/commands/packages.py, arches_controlled_lists/media/js/views/components/plugins/controlled-list-manager.js, arches_controlled_lists/models.py, arches_controlled_lists/src/arches_controlled_lists/components/ControlledListsMain.vue, arches_controlled_lists/src/arches_controlled_lists/components/MainSplitter.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/AddMetadata.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/AddValue.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ImageEditor.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ImageMetadata.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ItemEditor.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ItemImages.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ItemURI.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ListCharacteristic.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ListEditor.vue, arches_controlled_lists/src/arches_controlled_lists/components/editor/ValueEditor.vue, arches_controlled_lists/src/arches_controlled_lists/components/tree/AddDeleteControls.vue, arches_controlled_lists/src/arches_controlled_lists/components/tree/ListTree.vue, arches_controlled_lists/src/arches_controlled_lists/components/tree/PresentationControls.vue, arches_controlled_lists/src/arches_controlled_lists/constants.ts, arches_controlled_lists/src/arches_controlled_lists/types.ts, arches_controlled_lists/src/arches_controlled_lists/utils.ts, arches_controlled_lists/views.py, package.json, pyproject.toml, tests/reference_datatype_tests.py
- Improve size of toast details
- Allow searching tree against any language's values
- Show confirm modal when navigating away from unsaved changes
- Restore focus to last editing element when cancelling unsaved changes modal
- Prevent initiating multiple edits
Some cosmetic updates also while I was poking around. Perhaps easier to review commit by commit.
=> Usability improvements for controlled list manager

arches_controlled_lists/media/js/views/components/widgets/reference-select.js, arches_controlled_lists/templates/views/components/widgets/reference-select.htm
`<select>` without a closing tag breaks things :( 
I also updated the js file to be more standard.
=> fixes reference select widget issues

arches_controlled_lists/settings.py, arches_controlled_lists/src/arches_controlled_lists/components/tree/TreeRow.vue
Closes #117
Before, when moving items to an item target in a new list, the code looked to the wrong data point (origin list, not target item's list) to determine the target list.
=> Fix list membership assignment when moving item #117

arches_controlled_lists/models.py, tests/test_views.py
When moving an item in the controlled list manager, parent information was being nulled out, causing problems calculating depth for the reference select widget, among others.
Closes #111
=> Fetch list items during resort operation #111

README.md, arches_controlled_lists/datatypes/datatypes.py, arches_controlled_lists/models.py, arches_controlled_lists/settings.py, arches_controlled_lists/src/arches_controlled_lists/types.ts, arches_controlled_lists/src/arches_controlled_lists/utils.spec.ts, arches_controlled_lists/src/arches_controlled_lists/utils.ts, arches_controlled_lists/src/arches_controlled_lists/widgets/ReferenceSelectWidget/ReferenceSelectWidget.vue, arches_controlled_lists/views.py, tests/fixtures/data/sample_list_api_response.json, tests/test_views.py
After #119 changed the meaning of `ListItem.sortorder` to be per sibling rather than per list, there were some follow-ups to handle:
- [Simplify sortorder calculation to renumber among siblings at 0](https://github.com/archesproject/arches-controlled-lists/commit/fc426ae8136c2c9228a23aa1b312659397d667eb)
- [Make flat list items endpoint return logical sort](https://github.com/archesproject/arches-controlled-lists/commit/cfbda4de4b36cabd95021aab6f2947b9ce9d2362)
- [Keep lookup_listitem_from_label() deterministic](https://github.com/archesproject/arches-controlled-lists/commit/67b22aabd2419da363ac786a6196a62e377a1650)
- [Create correct sortorder value on POST](https://github.com/archesproject/arches-controlled-lists/commit/d6b376121088061f45878bcfe1fe428eb01876db)
I happened to have …
=> Address tech debt from redefining sortorder to apply across siblings only

arches_controlled_lists/apps.py, arches_controlled_lists/datatypes/datatypes.py
Incoming JSON from the DRF API now deserializes to `Reference` objects in python.
This fixes the issue reported in a recent lingo standup about `dict`s not being handled in `transform_value_for_tile()`, since now they're `Reference` objects.
Also provides a model for how to do this for other custom datatypes, e.g in HERs etc.
=> Register custom serializer field for reference DT

pyproject.toml
Combining usage of github urls with and without the .git extension to point to dependency branches can cause a conflict even if the branch is the same. This occurred in an application using both controlled lists and modular reports because controlled lists uses the extension and modular reports doesn't. 
```
ERROR: Cannot install casf-database because these package versions have conflicting dependencies.
The conflict is caused by:
arches-controlled-lists 1.0.0b1 depends on arches-component-lab 0.0.1a2 (from git+https://github.com/archesproject/arches-component-lab.git@main)
arches-modular-reports 1.0.0b2.dev0 depends on arches-component-lab 0.0.1a2 (from git+https://github.com/archesproject/arches-component-lab@main)
To fix this you could try to:
1. loosen the range of package versions …
```
=> Use same url pattern as modular reports
